const MARKER_TAG = 'wake-alarm:intents';
const MARKER_REVISION = 'r1';
const begin = (part) =>
  `// >>> ${MARKER_TAG} ${MARKER_REVISION} ${part} — generated by react-native-wake-alarm; edit the plugin, not this file`;
const end = (part) => `// <<< ${MARKER_TAG} ${part}`;
const regionRe = (part) =>
  new RegExp(
    `[ \\t]*// >>> ${MARKER_TAG} [^ ]+ ${part} [^\\n]*\\n[\\s\\S]*?[ \\t]*// <<< ${MARKER_TAG} ${part}[^\\n]*\\n`,
    'g'
  );
const ANCHOR = /didFinishLaunchingWithOptions[^{]*\{\s*\n/;
// Line-anchored so a comment or string containing "import " is never taken for the import block.
const FIRST_IMPORT = /^import\s/m;

const IMPORT = `${begin('import')}\nimport WakeAlarm\n${end('import')}\n`;
const CALL = `    ${begin('call')}\n    WakeAlarmIntentsRegistration.install()\n    ${end('call')}\n`;

function injectAppDelegate(contents) {
  if (
    contents.includes(`${MARKER_TAG} ${MARKER_REVISION} import`) &&
    contents.includes(`${MARKER_TAG} ${MARKER_REVISION} call`)
  )
    return contents;
  let out = contents
    .replace(regionRe('import'), '')
    .replace(regionRe('call'), '');
  const match = ANCHOR.exec(out);
  if (!match)
    throw new Error(
      'react-native-wake-alarm: could not find didFinishLaunchingWithOptions in AppDelegate.swift'
    );
  const insertAt = match.index + match[0].length;
  out = out.slice(0, insertAt) + CALL + out.slice(insertAt);
  const firstImport = FIRST_IMPORT.exec(out);
  if (!firstImport)
    throw new Error(
      'react-native-wake-alarm: could not find an import line in AppDelegate.swift'
    );
  out = out.slice(0, firstImport.index) + IMPORT + out.slice(firstImport.index);
  return out;
}

module.exports = { injectAppDelegate, MARKER_REVISION };
